services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: voting_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: voting_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "${DB_PORT}:5432"
    networks:
      - voting-network

  voting-api:
    build: ./api-server
    depends_on:
      - postgres
    restart: always
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=voting_db
      - DB_USER=postgres
      - DB_PASSWORD=voting_password_123
    ports:
      - "${API_PORT}:3001"
    networks:
      - voting-network

  voting-app:
    build: ./voting-app
    depends_on:
      - voting-api
    environment:
      - REACT_APP_API_URL=http://voting-api:${API_PORT}
      - REACT_APP_DASHBOARD_URL=http://localhost:${DASHBOARD_PORT}
    ports:
      - "${FRONTEND_PORT}:3000"
    networks:
      - voting-network

  dashboard:
    build: ./dashboard
    depends_on:
      - voting-api
    environment:
      - REACT_APP_API_URL=http://voting-api:${API_PORT}
    ports:
      - "${DASHBOARD_PORT}:3000"
    networks:
      - voting-network

volumes:
  postgres_data:

networks:
  voting-network:
    driver: bridge
