# version 제거 + healthcheck 제거
services:
  voting-api:
    build: ./api-server
    container_name: voting-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    networks:
      - voting-network
    restart: unless-stopped

  voting-app:
    build: ./voting-app
    container_name: voting-frontend
    ports:
      - "3000:3000"
    depends_on:
      - voting-api
    environment:
      - REACT_APP_API_URL=http://voting-api:3001
    networks:
      - voting-network
    restart: unless-stopped

networks:
  voting-network:
    driver: bridge