apiVersion: v1
kind: Namespace
metadata:
  name: voting-system
  labels:
    name: voting-system
---
# 사용자별 네임스페이스 템플릿
apiVersion: v1
kind: Namespace
metadata:
  name: ${USER_ID}-voting
  labels:
    name: ${USER_ID}-voting
    user: ${USER_ID}