apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: user1-voting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-api
  template:
    metadata:
      labels:
        app: voting-api
    spec:
      containers:
      - name: voting-api
        image: user1-voting-api:latest
        imagePullPolicy: Never  # 로컬 이미지 사용
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: voting-config
              key: NODE_ENV
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: voting-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: voting-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: voting-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: voting-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voting-secret
              key: DB_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: user1-voting
spec:
  selector:
    app: voting-api
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
---
# NodePort 서비스 (외부 접속용)
apiVersion: v1
kind: Service
metadata:
  name: api-nodeport
  namespace: user1-voting
spec:
  selector:
    app: voting-api
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30011
  type: NodePort